Add an upgrade script for revpi nodes via npm
RevolutionPi/noderedrevpinodes-server pull request #8
Opened 2023-05-22 11:21 UTC by naruxde

This change packages the appropriate node-red-contrib-revpi-nodes version into the noderedrevpinodes-server package. In the first step, this archive is only installed on the target system. In addition, an update script is provided that allows the user to update the existing NodeRED installation with the provided node version. The user rights must be observed.

2023-05-22 12:01 UTC, tboehler1 requested changes

2023-05-22 12:01 UTC, tboehler1 commented on debian/node-red-contrib-revpi-nodes/update-node-red-revpi-nodes
> +# Copyright: 2023 KUNBUS GmbH
This should be replaced with `SPDX-FileCopyrightText: 2023 KUNBUS GmbH`

2023-05-22 12:01 UTC, tboehler1 commented on debian/node-red-contrib-revpi-nodes/update-node-red-revpi-nodes
> +    echo "NodeRED is not installed at '${NODE_RED_ROOT}'"
Redirect errors to `stderr`: `>&2`

2023-05-22 12:01 UTC, tboehler1 commented on debian/node-red-contrib-revpi-nodes/update-node-red-revpi-nodes
> +# SPDX-License-Identifier: GPL-2.0
SPDX License Identifier `GPL-2.0` is deprecated, use `GPL-2.0-only` or `GPL-2.0-or-later` instead.

https://spdx.org/licenses/GPL-2.0.html

2023-05-22 12:01 UTC, tboehler1 commented on debian/node-red-contrib-revpi-nodes/update-node-red-revpi-nodes
> +    /usr/bin/sudo -u pi "${0}"
I don't really like doing this as part of the script. Rather, I think it should be run by root like this in the first place if root is running this.
Feel free to disagree :p

2023-05-22 12:01 UTC, tboehler1 commented on debian/node-red-contrib-revpi-nodes/update-node-red-revpi-nodes
> +    echo "This script must be executed as user pi or root."
Redirect to `stderr`

2023-05-22 12:19 UTC, LukasZech requested changes

2023-05-22 12:19 UTC, LukasZech commented on debian/node-red-contrib-revpi-nodes/update-node-red-revpi-nodes
> +#!/bin/bash
Is there a convention wether to use

`#!/bin/sh`
or
`#!/bin/bash`
?

I could find both in multiple scripts in our repositories

2023-05-22 12:19 UTC, LukasZech commented on debian/node-red-contrib-revpi-nodes/update-node-red-revpi-nodes
> +        --save --save-exact \
`--save-exact` has no effect for packages installed from a tarball as the version in the package.json will simply be set to the filename of the tarball

2023-05-22 12:19 UTC, LukasZech commented on debian/node-red-contrib-revpi-nodes/update-node-red-revpi-nodes
> +        --save --save-exact \
`--save` is the default and its not necessary to provide it 
although imho it does not hurt here to make clear that this save to the package.json in the target dir

2023-05-22 12:45 UTC, naruxde commented on debian/node-red-contrib-revpi-nodes/update-node-red-revpi-nodes
> +#!/bin/bash
On a debian system the /bin/sh is linked to the dash. The differences are probably in the range of functions, in dealing with variables, etc. However, the Bash is specified as Essential in Debian, which is defined as the minimal set of functionality that must be available and usable on the system at all times. Don't know 🤷

2023-05-22 12:45 UTC, LukasZech commented
I don't quite understand the general approach of this.

If you just want to install a fixed version of the package, you could simply use
`npm install --save-exact node-red-contrib-revpi-nodes@1.1.0`

or if you want to install a version from the repository that was not yet release to npm (like v1.1.10) you can still install the tarball via url from there.

The problem with this approach is, that it changes the `/home/pi/.node-red/package.json` in a way, that it can never be updated though npm again as it replaces the version of the dependency with the path to the local tarball.


If you just want to enforce that a only specific version of a package is use on your system, simply install it as global dependency and remove the local dependency from `/home/pi/.node-red/package.json` alltogheter.

That would be a more proper approach than manipulating the dependencies of another package by installing a script in a different package from to different package manager to circumvent npm

`npm install --global node-red-contrib-revpi-nodes@1.1.0`

for the global package it could even make sense to use the included tarball

2023-05-22 12:45 UTC, tboehler1 commented on debian/node-red-contrib-revpi-nodes/update-node-red-revpi-nodes
> +#!/bin/bash
My default is using POSIX sh and switching to bash if needed, but I don't know how others handle this.

I was wondering, in this case and generally, if we should use `#!/bin/bash` or `#!/usr/bin/env bash` for bash.

2023-05-22 12:51 UTC, iluminat23 commented on debian/node-red-contrib-revpi-nodes/update-node-red-revpi-nodes
> +    /usr/bin/sudo -u pi "${0}"
> I don't really like doing this as part of the script. Rather, I think it should be run by root like this in the first place if root is running this. Feel free to disagree :p
As the intention is **not** running as root, your assumption is wrong.

But I would run this with `su` not `sudo`.

2023-05-22 12:52 UTC, iluminat23 commented on debian/node-red-contrib-revpi-nodes/update-node-red-revpi-nodes
> +    /usr/bin/sudo -u pi "${0}"
Or just bail if the wrong user is running the script.

2023-05-22 12:57 UTC, LukasZech commented
Another approach would be to provide the package from the  `noderedrevpinodes-server` folder itself by including it in the source and link the dependency locally by using [npm link](https://docs.npmjs.com/cli/v9/commands/npm-link) which is  " handy for installing your own stuff" as the documentation quotes

2023-05-22 13:01 UTC, tboehler1 commented on debian/node-red-contrib-revpi-nodes/update-node-red-revpi-nodes
> +    /usr/bin/sudo -u pi "${0}"
> Or just bail if the wrong user is running the script.

This is what I mean. If the user `pi` should be running this then that user should be the only one calling it. root can achieve this with `su` if it really wants too, but this should be done *explicitly*.

2023-05-22 13:01 UTC, naruxde commented
> Another approach would be to provide the package from the `noderedrevpinodes-server` folder itself by including it in the source and link the dependency locally by using [npm link](https://docs.npmjs.com/cli/v9/commands/npm-link) which is " handy for installing your own stuff" as the documentation quotes

I like that! Take a branch and show us how!

2023-05-22 13:07 UTC, tboehler1 approved these changes
The implementation is fine by me.

2023-05-22 13:50 UTC, LukasZech commented
> > Another approach would be to provide the package from the `noderedrevpinodes-server` folder itself by including it in the source and link the dependency locally by using [npm link](https://docs.npmjs.com/cli/v9/commands/npm-link) which is " handy for installing your own stuff" as the documentation quotes
> 
> I like that! Take a branch and show us how!

@naruxde 
here you go

https://github.com/RevolutionPi/noderedrevpinodes-server/pull/9

2023-05-22 13:53 UTC, iluminat23 commented
This will ultimately kill any installation without internet access. Or am I mistaken?

2023-05-22 14:07 UTC, LukasZech commented
including the node-red-contrib-revpi-nodes npm package in the noderedrevpinodes-server debian package makes the process completely offline.

the node-red-contrib-revpi-nodes npm package will then be updated with each new version of the noderedrevpinodes-server debian package

if the debian package is available then the node-red-contrib-revpi-nodes npm package is as well, as nothing is acutally installed via npm, at least using the `npm link` approach

installing the tarball via npm will install the dependencies listed in the package.json of the node-red-contrib-revpi-nodes npm package, although this is only because they are not declared correctly. If they were declared as peerDependency then nothing would need to be installed via npm at all

2023-05-23 12:57 UTC, LukasZech approved these changes

2023-05-24 12:28 UTC, LukasZech commented
According to the documentation, it should not be necessary to install the nodes as npm package at all.
It seems to be sufficient if the files are present in the `nodesDir` folder
https://nodered.org/docs/user-guide/runtime/configuration
https://github.com/node-red/node-red/pull/3676


It should be enough to simply replace the `npm install tarball.tar.gz` with `untar tarball.tar.gz. /home/pi/.node-red/nodes`

2023-05-24 13:14 UTC, LukasZech commented
just tested it and this works:
 ```

mkdir -p /home/pi/.node-red/nodes
tar -xf 1.1.0.tar.gz -C /home/pi/.node-red/nodes
```
after extracting the tar to this folder and restarting the node-red server the nodes are available in node-red without the need to use npm at all

2023-05-24 14:12 UTC, iluminat23 commented
OK, this needs to be done by the user. We will never add anything to a package which installs something to the home of the user.
May be an update script invoked by the user?

2023-05-24 14:36 UTC, naruxde commented
But what about putting it to `/usr/lib/node_modules/`? Will this work for the node-red installation, too? Is that a kind of global library storage on a debian system? Link for example `/usr/lib/python3/dist-packages/` for python 3? @LukasZech

2023-05-25 07:20 UTC, naruxde commented
All the solutions mentioned are wrong. We now need to focus on how to install the `node-red-contrib-revpi-nodes` in `/usr/lib/node_modules/node-red/node_modules`.

2023-05-25 07:20 UTC, closed without merging